### ISSUE TITLE
How to add modpacks

### ISSUE THREAD

**Issue by 8qBITs** [steevLP/slpmodslauncher#3]
So in your docs you described modpack structure, rest API structure tho there is no mentions of where we add the link to the api

**Comment by steevLP** [comment]
I will edit that when i have time

**Comment by steevLP** [comment]
but as i said in discord 
all you need todo is edit the config point "all" in assets/config/app.json
the structure shown in the wiki is the same and in all you need to display all modpacks

**Comment by 8qBITs** [comment]
Wrote this before i contacted you all solved!
